### ISSUE TITLE
Cannot launch on Mac

### ISSUE THREAD

**Issue by aienabled** [nconrad/idasen-desk-controller#7]
Hello!
Alas, there is no guide how to use it.

It's stuck on an empty white window. From the Terminal log:
```
/Applications/Electron.app/Contents/MacOS/Electron /Downloads/idasen-desk-controller-master/main.js
(node:35471) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'url' before initialization
    at createWindow (/Downloads/idasen-desk-controller-master/main.js:15:49)
(node:35471) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:35471) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Electron v10.1.1

I've tried it launching with npm (`npm install` then `npm start`) but got:
```
npm install
npm WARN engine styled-components@5.2.0: wanted: {"node":">=10"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine wait-on@5.2.0: wanted: {"node":">=8.9.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine parcel@1.12.4: wanted: {"node":">= 6.0.0"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN engine electron@9.3.0: wanted: {"node":">= 8.6"} (current: {"node":"0.10.36","npm":"1.4.28"})
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache/add-named.js:203:12
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 18.6.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Downloads/idasen-desk-controller-master
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code E405
npm ERR! not ok code 0



npm start

> idasen-controller@0.9.1 start /Downloads/idasen-desk-controller-master
> parcel ./src/index.html --open

sh: parcel: command not found

npm ERR! idasen-controller@0.9.1 start: `parcel ./src/index.html --open`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the idasen-controller@0.9.1 start script.
npm ERR! This is most likely a problem with the idasen-controller package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     parcel ./src/index.html --open
npm ERR! You can get their info via:
npm ERR!     npm owner ls idasen-controller
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 18.6.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Downloads/idasen-desk-controller-master
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Downloads/idasen-desk-controller-master/npm-debug.log
npm ERR! not ok code 0
```

**Comment by aienabled** [comment]
It does work fine after installing the latest update from https://nodejs.org/en/
I wish there is an inch/cm mode selection. Please keep working on it!

Regards!
